### PR TITLE
return instance_dice of 0.0 instead of NaN when missing predictions

### PR DESCRIPTION
**Pull request by JosefBuchner**
Handles edge case of 0 true positives: return instance_dice = 0.0 instead of NaN.

### CODE REVIEW

**Comment by JosefBuchner** [comment]
Updated mean instance dice formula to account for missed instances

**Comment by neuronflow** [comment]
"
Updated mean instance dice formula to account for missed instances
"
Such a metric needs a separate PR (from a different branch). I also thought about including missed instances here.

The idea here is to keep this analogue to `segmentation_quality` from the panoptic segmentation paper:
https://arxiv.org/pdf/1801.00868.pdf

Screenshot 2023-11-07 at 19 48 55


What I do not like about the original SQ is that it is based on IOU. The idea behind this instance dice was to have a DICE-based metric, which is more comparable to the volumetric voxel-wise DSC, that is reported for most datasets.

**Review by neuronflow — CHANGES_REQUESTED** [review]
no, see: https://github.com/BrainLesion/panoptica/pull/9#issuecomment-1799538272

**Comment by neuronflow** [comment]
One could also consider multiplying it with F1 analogue to the panoptic segmentation paper.

**Review by JosefBuchner — COMMENTED** [review]
Reverted proposed changes

**Comment by neuronflow** [comment]
lgtm, what do you think @Hendrik-code ?

**Review by neuronflow — APPROVED** [review]

**Pull request merged**
